<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CitasApp.Application\CitasApp.Application.csproj" />
		<ProjectReference Include="..\CitasApp.Domain\CitasApp.Domain.csproj" />
		<ProjectReference Include="..\CitasApp.Infrastructure\CitasApp.Infrastructure.csproj" />
	</ItemGroup>

</Project>